apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  namespace: valkey
data:
  valkey.conf: |
    port 6379
    appendonly yes

    loadmodule "/usr/lib/valkey/libsearch.so" --use-coordinator

    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000

    save 60 1000
